-- Seed sample movies for testing
INSERT INTO public.movies (
  title,
  description,
  director,
  actors,
  year,
  category,
  resolution,
  file_size,
  poster_url,
  backdrop_url,
  stream_url,
  is_premium,
  is_featured
) VALUES 
(
  'Inception',
  'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
  'Christopher Nolan',
  ARRAY['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy'],
  2010,
  'Action',
  '4K',
  '4.2 GB',
  'https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Ber.jpg',
  'https://image.tmdb.org/t/p/original/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
  true,
  true
),
(
  'Parasite',
  'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
  'Bong Joon-ho',
  ARRAY['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik'],
  2019,
  'K-Drama',
  '1080p',
  '2.8 GB',
  'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
  false,
  false
),
(
  'The Dark Knight',
  'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
  'Christopher Nolan',
  ARRAY['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine'],
  2008,
  'Action',
  '4K',
  '3.9 GB',
  'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
  true,
  false
),
(
  'Squid Game',
  'Hundreds of cash-strapped players accept a strange invitation to compete in childrens games. Inside, a tempting prize awaits with deadly high stakes.',
  'Hwang Dong-hyuk',
  ARRAY['Lee Jung-jae', 'Park Hae-soo', 'Wi Ha-jun', 'Jung Ho-yeon'],
  2021,
  'K-Drama',
  '1080p',
  '2.1 GB',
  'https://image.tmdb.org/t/p/w500/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg',
  'https://image.tmdb.org/t/p/original/oLB6J8RkQnL9m5qQZ0FDxTFetXh.jpg',
  NULL,
  true,
  false
),
(
  'Interstellar',
  'A team of explorers travel through a wormhole in space in an attempt to ensure humanitys survival.',
  'Christopher Nolan',
  ARRAY['Matthew McConaughey', 'Anne Hathaway', 'Jessica Chastain', 'Michael Caine'],
  2014,
  'Sci-Fi',
  '4K',
  '5.1 GB',
  'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
  'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
  false,
  false
),
(
  'Train to Busan',
  'While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.',
  'Yeon Sang-ho',
  ARRAY['Gong Yoo', 'Jung Yu-mi', 'Ma Dong-seok', 'Kim Su-an'],
  2016,
  'Horror',
  '1080p',
  '2.4 GB',
  'https://image.tmdb.org/t/p/w500/2zOl3HEq91DVfFPGfXPWqhTetth.jpg',
  'https://image.tmdb.org/t/p/original/pnHC1VnkvccXmShRVQvfkqYBqpR.jpg',
  'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
  false,
  false
);