// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmpfiquvcnybmjthcaml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tcGZpcXV2Y255Ym1qdGhjYW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3ODI4NDQsImV4cCI6MjA3NTM1ODg0NH0.6fHJ8qCWsDqrQCIHRSqWxjdURjZsGO7tSixpL8pxP-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});