// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orvctyhsjefhxncxxsrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ydmN0eWhzamVmaHhuY3h4c3JiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNzU4NDEsImV4cCI6MjA4NTc1MTg0MX0.FUfeQm1APVpPEcJGewysV9YIhJcbAdS7hhMBawJIFYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});